### ISSUE TITLE
Pypi test

### ISSUE THREAD

**Issue by astrom-tom** [psincraian/pepy#113]
Dear @psincraian,

Thank you for this website it is amazing! 
I have two questions:
-I was wondering how difficult it would be to implement the same for the pypi-test repository?
-When are the counts updated? and how are they made?

Cheers,

**Comment by psincraian** [comment]
Hi @astrom-tom,

Regarding your first question I don't know how difficult it would be to implement it in pypi-test repository because I don't know it's codebase.

The counts are updated each day at 5pm UTC. There are retrieved from the official bigquery repository: https://packaging.python.org/guides/analyzing-pypi-package-downloads/

If you have any other question I will be glad to answer it, otherwise I will close the issue :blush:

**Comment by brainwane** [comment]
@psincraian Would it be possible to add that info to the README?

**Comment by psincraian** [comment]
Done :-)
