### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by peterdemin** [psincraian/pepy#17]
Nicely done! Thank you!
I'd like to put pepy badge on GitHub README, but I can't, because HTTP resources can't be fetched from HTTPS pages.

**Comment by psincraian** [comment]
The badge already works on GitHub because it uses the camo project https://github.com/atmos/camo to serve all the images. Here are some examples that uses the badge in README https://github.com/psincraian/climoji or https://github.com/kibitzr/kibitzr

Also, I am working to add HTTPS support to http://pepy.tech, maybe this weekend I will have it implemented :blush:

**Comment by peterdemin** [comment]
Good luck with that! Also, https://github.com/kibitzr/kibitzr is my project, I saw it replaces URL with camo stuff, but at the moment of writing, camo returned 504.
I put README on https://pypi.org/project/kibitzr/, and I guess PyPI doesn't have this mechanism.

**Comment by psincraian** [comment]
First of all nice project! :blush: 

This project https://pypi.org/project/pysxm/ uses the badge and in the PyPI website it shows correct. You need to add a new version of the package and upload it to PyPI, did you do that?

**Comment by psincraian** [comment]
Now we have https support :rocket: 

Check https://pepy.tech/ :blush:

**Comment by peterdemin** [comment]
Thanks! Awesome!

**Comment by kylebarron** [comment]
@psincraian 

You should update your stackoverflow answer to use HTTPS
https://stackoverflow.com/a/49214128

**Comment by psincraian** [comment]
@kylebarron done, thanks :blush:
