### ISSUE TITLE
Service crashed too frequently

### ISSUE THREAD

**Issue by Tumao727** [psincraian/pepy#418]
This tool is really awesome! I generate download stats with it everyday. Then I found that service crashes about twice or 3 times every month since I used. Is it possible to improve its stability?

**Comment by Tumao727** [comment]
<img width="897" alt="截屏2022-03-02 上午10 03 49" src="https://user-images.githubusercontent.com/20420181/156280639-a84b0b59-321b-44e9-8929-75c38b9b5933.png">

**Comment by psincraian** [comment]
Hey @Tumao727,

First, sorry for the inconvenience. The main problem is that our single server is running out of memory and it kills the mongodb instance. This happens usually when there is a spike of traffic.

Currently we are on a 20$ droplet on DigitalOcean with 4 GB of ram and 2 vCPU. This single server handles more than 8 million requests per month!

This server is partially paid by the ads that we are running and I pay the rest :-) before there were some sponsors that contributed that I'm very grateful because it helped paying the full bills!

I would like to increase the capacity to handle more requests, but this means more money and I don't want to increase my personal bill.

**Comment by Tumao727** [comment]
@psincraian  Got it. Project requires time and money. Thanks for your effort.

**Comment by maxbachmann** [comment]
> Currently we are on a 20$ droplet on DigitalOcean with 4 GB of ram and 2 vCPU. This single server handles more than 8 million requests per month!

> This server is partially paid by the ads that we are running and I pay the rest :-) before there were some sponsors that contributed that I'm very grateful because it helped paying the full bills!

@psincraian do you already make use of the Open Source program of Digital Ocean. This should cover at least part of the costs your facing: https://docs.google.com/document/d/1P1ZqpxgKtiNibtWs53dLeCBmfp47Nqi6QlRg74lbsAc/edit#heading=h.vgxseueif2te

**Comment by yzhao062** [comment]
is there a way we could make a one-time donation to the project other than the Patreon? nice work btw!

**Comment by psincraian** [comment]
Hey @maxbachmann thanks for the tip! Sincerely, I didn't know about this program.


Hey @yzhao062 I have [paypal](https://www.paypal.com/paypalme/psincraian) or you can also use [buymeacoffe](https://www.buymeacoffee.com/pepy)

**Comment by yzhao062** [comment]
@psincraian Great! Just showed some appreciation via paypal. Thanks for this great project!

**Comment by psincraian** [comment]
Many thanks for your support @yzhao062 I really appreciate it 😊😊🤗🤗
