### ISSUE TITLE
Plot downloads by week

### ISSUE THREAD

**Issue by janluke** [psincraian/pepy#487]
Daily download are noisy and plunge during the weekend. Plotting weekly downloads would be much more useful to spot trends.

**Comment by erikwrede** [comment]
Gave it a try here https://github.com/psincraian/pepy-front/pull/438
Still a draft so any feedback is welcome 🙂

**Comment by psincraian** [comment]
Now this feature is live! Many thanks @erikwrede for delivering this feature :blush:

**Comment by hugovk** [comment]
This is great, thank you very much!

For the weekly chart, may I suggest the first, partial week is left out?

For [example](https://pepy.tech/project/pillow?display=weekly&versions=*), the first point is labelled Thursday:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1324225/209798549-c95f2cec-1d59-4f02-a8a4-91c759d301e4.png">

And the next and subsequent points are all Sundays:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/1324225/209798613-1aa99e18-f69c-4f2c-b7f0-2289f0061b8b.png">

That initial half-week is a bit misleading, and there's enough full weekly data points that we can leave it out and still have a good chart.

(The final dip looks like a natural dip caused by Christmas holidays.)

Thanks!

**Comment by psincraian** [comment]
I think to fix all of this issues I will add an option to select the range of dates. Another person mentioned that there is too much data and is difficult to focus on smaller range
